### ISSUE TITLE
Title not showing in Report and List View

### ISSUE THREAD

**Issue by joezsweet** [mxmo-co/title_links#6]
Hi there, 

i got an issue when using link field in `Reports` and `ListViews`, see pics:

It shows correctly in widget:

<img width="806" alt="schermata 2017-02-09 alle 22 11 36" src="https://cloud.githubusercontent.com/assets/11652845/22805112/508e4740-ef1c-11e6-9d66-4a5bc110fc0a.png">

when you choose the field, it shows the `name` instead of the `title`:

<img width="796" alt="schermata 2017-02-09 alle 22 11 56" src="https://cloud.githubusercontent.com/assets/11652845/22805111/5060dbc0-ef1c-11e6-9eab-c9b7d77c76eb.png">

In List View it seems to be the same prob, you can see **Reparto** is showing **C-008**:

<img width="1171" alt="schermata 2017-02-09 alle 23 09 21" src="https://cloud.githubusercontent.com/assets/11652845/22805213/d57aa430-ef1c-11e6-8e9b-13b38eefb29b.png">

instead of **ORTOFRUTTA**

<img width="1184" alt="schermata 2017-02-09 alle 23 10 14" src="https://cloud.githubusercontent.com/assets/11652845/22805258/f9049866-ef1c-11e6-9d66-7ae97e51afb6.png">

**Comment by MaxMorais** [comment]
@joezsweet, I'm publishing a small fix, that should solve the issue in the 1st and 2nd screenshots, if fixed too a bad entry in `hooks.py` that is not remplacing the template in the list views, to the right list views!

I this that these 2 small fixes are enought to you get it fixed!

**Comment by joezsweet** [comment]
Thx, i'll test and get back

**Comment by joezsweet** [comment]
On Report filter now i'm getting:

<img width="814" alt="schermata 2017-02-10 alle 08 29 01" src="https://cloud.githubusercontent.com/assets/11652845/22818023/2450395a-ef6b-11e6-9a00-e7b615b96e7c.png">

While on List View nothing changed, still getting the code:

<img width="1171" alt="schermata 2017-02-09 alle 23 09 21" src="https://cloud.githubusercontent.com/assets/11652845/22818044/46db59fa-ef6b-11e6-85d6-8e5c77a204a8.png">

**Comment by joezsweet** [comment]
Working fine except for **Reports**

**Comment by MaxMorais** [comment]
@joezsweet another fixes was published, it will solve all issues, I think!

**Comment by joezsweet** [comment]
I'm on last version, problem on **Reports** is still there

**Comment by MaxMorais** [comment]
@joezsweet more fixes are published!

**Comment by joezsweet** [comment]
@MaxMorais  ..no way ..on **Report** it doesn't work :(

**Comment by MaxMorais** [comment]
@joezsweet that's a bit crazy, but I'm finally forcing the right function call everywhere!

**Comment by joezsweet** [comment]
@MaxMorais still problem om **Reports**, now field keep waiting for the value, see pics:

<img width="798" alt="schermata 2017-02-11 alle 09 20 15" src="https://cloud.githubusercontent.com/assets/11652845/22852412/0792f79a-f03c-11e6-8b79-a95d2a6b631b.png">

<img width="871" alt="schermata 2017-02-11 alle 09 20 26" src="https://cloud.githubusercontent.com/assets/11652845/22852411/0783763a-f03c-11e6-9317-7b0b6581dd4c.png">

**Comment by MaxMorais** [comment]
@joezsweet I'll close this issue for now, seens fixed!

**Comment by joezsweet** [comment]
k
